name: backend build & smoke test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install Dependencies
        working-directory: backend
        run: npm ci

      - name: Start server & wait for port 3000
        working-directory: backend
        run: |
          nohup npm run fullstart &> server.log &
          echo "Waiting up to 20s for server to respond..."
          for i in {1..10}; do
            if curl --fail --silent http://localhost:3000/; then
              echo "Server is up!"
              exit 0
            fi
            sleep 2
          done
          echo "Server failed to start in time"
          cat server.log
          exit 1

      

